## How to do integer encoding using keras

In [1]:
import numpy as np

In [2]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [4]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='<nothing>')

In [6]:
# We are using tokenizer to assign an unique id to each word
# We mostly use word tokenizer

tokenizer.fit_on_texts(docs)

In [7]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [8]:
# Getting the count of each word

tokenizer.word_counts

OrderedDict([('recurrent', 2),
             ('neural', 8),
             ('network', 6),
             ('artificial', 2),
             ('connections', 2),
             ('between', 2),
             ('nodes', 4),
             ('can', 2),
             ('create', 2),
             ('a', 2),
             ('cycle', 2),
             ('allowing', 2),
             ('output', 2),
             ('some', 2),
             ('to', 2),
             ('affect', 4),
             ('subsequent', 4),
             ('exhibit', 2),
             ('temporal', 2),
             ('dynamic', 2),
             ('behavior', 2),
             ('type', 2),
             ('of', 2)])

In [9]:
# Getting the unique word count

tokenizer.document_count

22

In [14]:
# Dimension of each sentense 

sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [15]:
# Adding padding to make eligible for input to network

from keras.utils import pad_sequences

In [16]:
sequences = pad_sequences(sequences,padding='post')

In [17]:
sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

## Sentiment Analysis

In [18]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [19]:
# Loading data

(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 2s 0us/step


In [20]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [21]:
print(len(X_train[2]))
print(len(X_train[3]))

141
550


In [22]:
# MAking dimension of input same

X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [23]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [25]:
# Input_shape as input 50 numbers in each sentense
# Output as 1 as negative or positive

model = Sequential()

model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [27]:
# Compiling model 
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 34s 42ms/step - loss: 0.6929 - accuracy: 0.5119 - val_loss: 0.6930 - val_accuracy: 0.5044
Epoch 2/5
782/782 [==============================] - 32s 41ms/step - loss: 0.6931 - accuracy: 0.5060 - val_loss: 0.6950 - val_accuracy: 0.5018
Epoch 3/5
782/782 [==============================] - 33s 42ms/step - loss: 0.6929 - accuracy: 0.5055 - val_loss: 0.6939 - val_accuracy: 0.5050
Epoch 4/5
782/782 [==============================] - 32s 41ms/step - loss: 0.6931 - accuracy: 0.5085 - val_loss: 0.6940 - val_accuracy: 0.5074
Epoch 5/5
782/782 [==============================] - 33s 43ms/step - loss: 0.6932 - accuracy: 0.5040 - val_loss: 0.6937 - val_accuracy: 0.5053


# How to do encodings using keras embeddings

In [28]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [29]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

In [30]:
tokenizer.fit_on_texts(docs)

In [31]:
len(tokenizer.word_index)

23

In [32]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[6, 1, 2],
 [1, 2],
 [7, 1],
 [8, 9, 3],
 [10, 11, 12, 13],
 [14, 15],
 [16, 3, 17, 4, 5],
 [18, 19],
 [20, 21],
 [22, 23, 1, 2],
 [4, 5]]

In [33]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 6,  1,  2,  0,  0],
       [ 1,  2,  0,  0,  0],
       [ 7,  1,  0,  0,  0],
       [ 8,  9,  3,  0,  0],
       [10, 11, 12, 13,  0],
       [14, 15,  0,  0,  0],
       [16,  3, 17,  4,  5],
       [18, 19,  0,  0,  0],
       [20, 21,  0,  0,  0],
       [22, 23,  1,  2,  0],
       [ 4,  5,  0,  0,  0]], dtype=int32)

In [34]:
model = Sequential()
model.add(Embedding(23,output_dim=2,input_length=5)) #Total vocab len, ouput dim(per word would be represend by 2 vector), input len per row

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              46        
                                                                 
Total params: 46
Trainable params: 46
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.compile('adam','accuracy')

In [36]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 101ms/step
[[[ 0.03064158  0.01701635]
  [-0.03214834 -0.00842739]
  [-0.03481197 -0.04845027]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]]

 [[-0.03214834 -0.00842739]
  [-0.03481197 -0.04845027]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]]

 [[ 0.00931837 -0.04935578]
  [-0.03214834 -0.00842739]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]]

 [[ 0.03957695  0.0162529 ]
  [-0.0025581   0.01641394]
  [-0.00677083 -0.04656874]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]]

 [[-0.00167454 -0.04946348]
  [-0.00659036 -0.02173336]
  [ 0.03815608  0.02122113]
  [ 0.01045545 -0.02768997]
  [ 0.03057839  0.0052469 ]]

 [[-0.02239708 -0.03635423]
  [ 0.02403    -0.025287  ]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]
  [ 0.03057839  0.0052469 ]]

 [[-0.00889545 -0.04352908]
  [-0.00677083 -0.04656874]
  [ 0.04472888  0.04046382]
  [ 0.03512

In [37]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [38]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [39]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [40]:
X_train.shape

(25000, 50)

In [41]:
# Considering 10000 words for embedding
# In embedding we convert the words to numbers

model = Sequential()
model.add(Embedding(10000,output_dim=2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 73s 92ms/step - loss: 0.6284 - acc: 0.6113 - val_loss: 0.4692 - val_acc: 0.7834
Epoch 2/5
782/782 [==============================] - 63s 80ms/step - loss: 0.4034 - acc: 0.8201 - val_loss: 0.4223 - val_acc: 0.8088
Epoch 3/5
782/782 [==============================] - 50s 64ms/step - loss: 0.3285 - acc: 0.8645 - val_loss: 0.4417 - val_acc: 0.8081
Epoch 4/5
782/782 [==============================] - 55s 71ms/step - loss: 0.2866 - acc: 0.8851 - val_loss: 0.4449 - val_acc: 0.8050
Epoch 5/5
782/782 [==============================] - 50s 64ms/step - loss: 0.2527 - acc: 0.9058 - val_loss: 0.5113 - val_acc: 0.7900


# Predictions

In [43]:
# Redhape the data to make data input ready

test_data = X_test[0][0:50].reshape(1,-1)

In [ ]:
model.predict(test_data)

1/1 [==============================] - 0s 116ms/step


array([[0.3815383]], dtype=float32)